# Generated by Django 3.2 on 2023-05-03 13:27

import django.contrib.auth.validators
from django.db import migrations, models

import recipes.validators
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230502_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[recipes.validators.validate_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[recipes.validators.validate_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='Необходимое поле. 150 или менее символов. Только буквы, цифры и эти символы: "@/./+/-/_" .', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), users.validators.validate_me_name], verbose_name='Имя пользователя'),
        ),
    ]
